stateDiagram-v2
    direction LR

    [*] --> TX_IDLE
    TX_IDLE     --> TX_SEND_STX: start(data,qtd)
    TX_SEND_STX --> TX_SEND_QTD
    TX_SEND_QTD --> TX_SEND_DATA: qtd>0
    TX_SEND_QTD --> TX_SEND_CHK:  qtd==0
    TX_SEND_DATA --> TX_SEND_CHK: idx==qtd
    TX_SEND_CHK  --> TX_SEND_ETX
    TX_SEND_ETX  --> TX_DONE
    TX_DONE      --> TX_IDLE
